[package]
name = "poc-actix-scalar"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
utoipa = { version = "4", features = ["actix_extras"] }
utoipa-scalar = { version = "0.1", features = ["actix-web"] }